name: Show Secrets from Repo and Environments

on:
  push:
    branches:
      - main

jobs:
  show_secrets_staging:
    runs-on: ubuntu-latest
    environment: staging # Uses staging environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display Staging Secrets
        run: |
          echo "🔑 Repo Secret API Key: ${{ secrets.API_KEY }}"
          echo "🗄️ Staging DB Secret (DB_KEY): ${{ secrets.DB_KEY }}"
          echo " stg app id: ${{ vars.APP_ID }}"
          echo " repo yt secret: ${{ vars.YT_KEY }}"

  show_secrets_production:
    runs-on: ubuntu-latest
    environment: production # Uses production environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display Production Secrets
        run: |
          echo "🔑 Repo Secret API Key: ${{ secrets.API_KEY }}"
          echo "🗄️ Production DB Secret (DB_KEY): ${{ secrets.DB_KEY }}"
          echo " prod app id: ${{ vars.APP_ID }}"
          echo " repo yt secret: ${{ vars.YT_KEY }}"

  show_secrets_without_environment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display Production Secrets
        run: |
          echo "🔑 Repo Secret API Key: ${{ secrets.API_KEY }}"
          echo "🗄️ Production DB Secret (DB_KEY): ${{ secrets.DB_KEY }}"
          echo " prod app id: ${{ vars.APP_ID }}"
          echo " repo yt secret: ${{ vars.YT_KEY }}"
